version: '3.8'
services:
  zerowave-portofolio:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    build: 
      context: '../nginx/.'
      dockerfile: Dockerfile
    ports:
      - '443:443'
    
    